#!/bin/env bash

RP_STARSHIP_CONFIG="[container]
symbol = '📦'
style = 'bold #A52B00 dimmed'
"
RP_STARSHIP_INIT_BASH='eval "$(starship init bash)'
RP_STARSHIP_INIT_ZSH='eval "$(starship init zsh)'
if [ ! -f ~/.config/rusty-pets/starship-activated ]; then
	echo "Activating starship prompt! ☄🌌️" 
    [ "${BASH_VERSION:-}" != "" ] && echo "${RP_STARSHIP_INIT_BASH}" > ~/.bashrc
    [ "${ZSH_VERSION:-}" != "" ] && echo "${RP_STARSHIP_INIT_ZSH}" > ~/.zshrc
	echo "${RP_STARSHIP_CONFIG}" > ~/.config/starship.toml
	touch ~/.config/rusty-pets/starship-activated
fi